# SwiftLint Configuration for Tiny Tastes Tracker
# Strict ruleset for code quality and consistency

# Paths to include/exclude
included:
  - TinyTastesTracker
excluded:
  - Pods
  - TinyTastesTracker/Resources/GenerativeAI-Info.plist
  - .build
  - DerivedData
  - build

# Opt-in rules (explicitly enable)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments during development
  - line_length # Handled by SwiftFormat

# Rule configurations
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Force unwrapping - ERROR level (must fix!)
force_unwrapping:
  severity: error

# Force cast - WARNING level
force_cast:
  severity: warning

# Force try - WARNING level
force_try:
  severity: warning

# Type name
type_name:
  min_length: 3
  max_length: 50
  severity: warning
  excluded:
    - ID

# Identifier name
identifier_name:
  min_length: 2
  max_length: 50
  severity: warning
  excluded:
    - id
    - ID
    - x
    - y
    - z
    - i
    - j
    - k

# Function body length
function_body_length:
  warning: 60
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

# Nesting
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  # Require space after comment start
  comment_spacing:
    name: "Comment Spacing"
    regex: "(//\S)"
    message: "Comments should have a space after //"
    severity: warning

  # Discourage print statements (use logging)
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\("
    match_kinds: identifier
    message: "Use proper logging instead of print()"
    severity: warning

  # Require TODO/FIXME to have ticket reference
  todo_with_ticket:
    name: "TODO with Ticket"
    regex: "(TODO|FIXME)(?!.*\\#\\d+)"
    message: "TODOs and FIXMEs should reference a ticket: TODO: #123"
    severity: warning

  # Discourage force unwrapping in production code
  force_unwrap_production:
    name: "Force Unwrap in Production"
    regex: "\\!(?![\\s\\)\\,\\:])"
    message: "Avoid force unwrapping. Use guard let or if let instead."
    severity: error
    excluded: ".*Tests\\.swift"

# Reporter
reporter: "xcode"

# Strict mode (fail on warnings)
strict: false

# Show rule identifiers in output
show_config_rules_in_violation: true
