name: TinyTastesTracker
options:
  bundleIdPrefix: com.tinytastes.tracker
  deploymentTarget:
    iOS: 17.0

packages:
  GoogleGenerativeAI:
    url: https://github.com/google/generative-ai-swift
    from: 0.4.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.22.0

targets:
  TinyTastesTracker:
    type: application
    platform: iOS
    sources:
      - TinyTastesTracker

    settings:
      base:
        INFOPLIST_FILE: TinyTastesTracker/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.tinytastes.tracker
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        CODE_SIGN_ENTITLEMENTS: TinyTastesTracker/TinyTastesTracker.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

    entitlements:
      path: TinyTastesTracker/TinyTastesTracker.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.tinytastes.tracker
    dependencies:
      - target: TinyTastesWidget
      - package: GoogleGenerativeAI
      - product: FirebaseAuth
        package: Firebase
      - product: FirebaseFirestore
        package: Firebase
      - product: FirebaseFirestoreSwift
        package: Firebase
      - product: FirebaseStorage
        package: Firebase
      - sdk: EventKit.framework
      - sdk: Network.framework


  TinyTastesWidget:
    type: app-extension
    platform: iOS
    sources:
      - TinyTastesWidget
      # Include specific shared models needed for the widget
      - path: TinyTastesTracker/Core/Models
      - path: TinyTastesTracker/Core/Utilities/Constants.swift
      - path: TinyTastesTracker/Core/Utilities/WidgetDataManager.swift
      - path: TinyTastesTracker/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: TinyTastesWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.tinytastes.tracker.widget
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        CODE_SIGN_ENTITLEMENTS: TinyTastesWidget/TinyTastesWidget.entitlements
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    entitlements:
      path: TinyTastesWidget/TinyTastesWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.tinytastes.tracker
    dependencies:
      - framework: WidgetKit
      - framework: SwiftUI
      - framework: AppIntents
      - product: FirebaseAuth
        package: Firebase
      - product: FirebaseFirestore
        package: Firebase
      - product: FirebaseFirestoreSwift
        package: Firebase

  TinyTastesTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TinyTastesTrackerTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tinytastes.tracker.tests
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TinyTastesTracker
      - package: GoogleGenerativeAI

  TinyTastesTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - TinyTastesTrackerUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tinytastes.tracker.uitests
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: TinyTastesTracker
    dependencies:
      - target: TinyTastesTracker
