//
//  ChartExporter.swift
//  TinyTastesTracker
//
//  Utility for exporting charts as images with metadata
//

import SwiftUI
import UIKit

struct ExportMetadata {
    let babyName: String
    let ageMonths: Int
    let chartType: String
    let dateRange: String?
    let generatedDate: Date = Date()
}

@MainActor
class ChartExporter {
    /// Export any chart view to a high-resolution image with metadata header
    static func exportChart<Content: View>(
        _ content: Content,
        metadata: ExportMetadata,
        size: CGSize = CGSize(width: 800, height: 600)
    ) -> UIImage? {
        // Create container with metadata header and footer
        let exportView = VStack(spacing: 20) {
            // Header with baby info
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    VStack(alignment: .leading, spacing: 4) {
                        Text(metadata.babyName)
                            .font(.system(size: 28, weight: .bold))
                        
                        Text("Age: \(metadata.ageMonths) months")
                            .font(.system(size: 16))
                            .foregroundStyle(.secondary)
                    }
                    
                    Spacer()
                    
                    VStack(alignment: .trailing, spacing: 4) {
                        Text(metadata.chartType)
                            .font(.system(size: 16, weight: .semibold))
                        
                        if let range = metadata.dateRange {
                            Text(range)
                                .font(.system(size: 14))
                                .foregroundStyle(.secondary)
                        }
                    }
                }
                
                Divider()
            }
            .padding(.horizontal)
            
            // Chart content
            content
                .frame(width: size.width, height: size.height)
            
            // Footer
            HStack {
                Text("Generated by TinyTastesTracker")
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
                
                Spacer()
                
                Text(metadata.generatedDate.formatted(date: .abbreviated, time: .shortened))
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
            }
            .padding(.horizontal)
        }
        .padding(30)
        .background(Color.white)
        .frame(width: size.width + 60, height: size.height + 200)
        
        // Render to high-resolution image
        let renderer = ImageRenderer(content: exportView)
        renderer.scale = 3.0  // 3x for retina displays
        
        return renderer.uiImage
    }
    
    /// Present share sheet for exporting/sharing an image
    static func shareImage(_ image: UIImage, from viewController: UIViewController?) {
        let activityVC = UIActivityViewController(
            activityItems: [image],
            applicationActivities: nil
        )
        
        // iPad popover configuration
        if let popover = activityVC.popoverPresentationController {
            popover.sourceView = viewController?.view
            popover.sourceRect = CGRect(x: UIScreen.main.bounds.midX, y: UIScreen.main.bounds.midY, width: 0, height: 0)
            popover.permittedArrowDirections = []
        }
        
        viewController?.present(activityVC, animated: true)
    }
    
    /// Save image directly to photo library
    static func saveToPhotos(_ image: UIImage, completion: @escaping (Bool, Error?) -> Void) {
        UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil)
        // Note: Requires "Privacy - Photo Library Additions Usage Description" in Info.plist
        completion(true, nil)
    }
}

// Helper to get the root view controller for presenting share sheets
extension ChartExporter {
    static func getRootViewController() -> UIViewController? {
        guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
              let rootVC = windowScene.windows.first?.rootViewController else {
            return nil
        }
        return rootVC
    }
}
